export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERR0R = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const SET_WATCHLIST = 'SET_WATCHLIST'
export const REMOVE_WATCHLIST_ITEM = 'REMOVE_WATCHLIST_ITEM'
export const SET_LOADING = 'SET_LOADING'
export const UPDATE_WATCHLIST_ITEM = 'UPDATE_WATCHLIST_ITEM'
